### ISSUE TITLE
question

### ISSUE THREAD

**Issue by TheBearodactyl** [zeozeozeo/geometrydash#4]
would it be ok if i used a bit of this code? I'm currently in the process of porting the entirety of Geode to Rust (i have a draft PR open on the repo if you wanna look), and i was hoping i might be able to use your `build.rs`?

**Comment by zeozeozeo** [comment]
yeah ofc! you can read more on making build.rs files for bindgen [here](https://rust-lang.github.io/rust-bindgen/tutorial-3.html)

**Comment by TheBearodactyl** [comment]
> yeah ofc! you can read more on making build.rs files for bindgen [here](https://rust-lang.github.io/rust-bindgen/tutorial-3.html)

thanks :D
